# Generated by Django 6.0.3 on 2026-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
